// frontend-react/src/App.js
import './App.css';
import {useEffect, useState} from "react";


function App() {
  const [, setCarboneFootprints] = useState(null)

  useEffect(() => {
    const url = "http://localhost:1337/carbone-footprints";
    fetch(url)
        .then(response => response.json())
        .then((data) => {
          setCarboneFootprints(data)
        })
        .catch((error) => {
          console.error(error)
        })
  }, []);

  return (
    <div className="App">
      <header className="App-header">
        <h1>Hello Michelle</h1>
        <p>Shall we start?</p>
      </header>
    </div>
  );
}

export default App;

// frontend/src/App.vue
<script setup>

async function logCarboneFootprints() {
  const url = "http://localhost:1337/carbone-footprints";
  const response = await fetch(url);
  const carboneFootprints = await response.json();
  console.log(carboneFootprints);
}

logCarboneFootprints()

</script>

<template>
  <header>
    Hello world
  </header>

  <main>
    Main content
  </main>
</template>

<style scoped>
</style>
